//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeccaWebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dispositivi
    {
        public string id { get; set; }
        public string descrizione { get; set; }
        public Nullable<int> tipo { get; set; }
        public string indirizzo { get; set; }
        public string matricola { get; set; }
    }
}
